name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemblePlayDebug assemblePlayDebugAndroidTest assemblePlayDebugUnitTest
    - name: Run unit tests
      run: ./gradlew testPlayDebugUnitTest
    - name: Add auth for flank
      env:
        GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
      run: |
        ./flank_auth.sh
    - name: Run UI tests
      run: ./gradlew runFlank
